config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="navbar">
  <h3>Simple Airbnb</h3>
  <button type="button" class="btn btn-outline-primary text-decoration-none">
    <%= link_to 'add flat', new_flat_path %>
  </button>
</div>

<div class="container">
  <h1>all our flats (<%= @flats.count %>)</h1>

    <div class="cards">
  <% @flats.each do |flat| %>
      <div class="flat_card">
        <img class="flat_card_img"src="https://source.unsplash.com/featured/?apartments" alt="a randomized room image">
        <h1><%= flat.name %></h1>
        <p><%= flat.address %></p>
        <div class="d-flex justify-content-between">
          <div class="d-flex">
            <i class="material-icons">people</i>
            <p class="mr-4"><%= flat.number_of_guests %></p>
          </div>
          <div class="d-flex">
            <i class="material-icons">attach_money</i>
            <p class="ml-4"><%= flat.price_per_night %></p>
          </div>
        </div>
        <p><%= link_to 'more info', flat_path(flat) %></p>
      </div>
  <% end %>
    </div>
</div>

name, as a string
address, as a string
description, as a text
price_per_night, as an integer
number_of_guests, as an integer

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>